export const recipes = [
  {
    id: 'carbonara',
    name: 'Spaghetti Carbonara',
    emoji: '🍝',
    tags: ['pasta', 'quick', 'comfort food'],
    time: '20 min',
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      '200g spaghetti',
      '100g pancetta or guanciale, diced',
      '2 large eggs + 1 yolk',
      '50g Pecorino Romano, finely grated',
      '50g Parmesan, finely grated',
      'Freshly ground black pepper',
      'Salt (for pasta water)',
    ],
    steps: [
      'Bring a large pot of salted water to a boil. Cook spaghetti until al dente, reserving a mug of pasta water before draining.',
      'While the pasta cooks, fry the pancetta in a cold pan over medium heat until the fat renders and it turns golden. Remove from heat.',
      'In a bowl, whisk together the eggs, yolk, and most of the cheese. Season generously with black pepper.',
      'Add the drained pasta to the pan with the pancetta (off the heat). Toss well.',
      'Pour the egg mixture over the pasta, adding a splash of pasta water and tossing quickly. The residual heat will cook the eggs into a creamy sauce — not scrambled. Add more pasta water as needed.',
      'Serve immediately with the remaining cheese and extra black pepper.',
    ],
  },
  {
    id: 'roast-chicken',
    name: 'Crispy Roast Chicken Thighs',
    emoji: '🍗',
    tags: ['meat', 'comfort food', 'oven'],
    time: '50 min',
    servings: 4,
    difficulty: 'Easy',
    ingredients: [
      '4 bone-in, skin-on chicken thighs',
      '2 tbsp olive oil',
      '4 garlic cloves, crushed',
      '1 tsp smoked paprika',
      '1 tsp dried oregano',
      '½ tsp chilli flakes',
      'Salt and black pepper',
      '1 lemon, halved',
    ],
    steps: [
      'Preheat oven to 220°C (200°C fan).',
      'Pat the chicken thighs dry with kitchen paper — this is key for crispy skin.',
      'Mix olive oil, garlic, paprika, oregano, and chilli flakes into a paste. Rub all over the chicken, getting under the skin where possible. Season well with salt and pepper.',
      'Place skin-side up in a roasting tray. Tuck the lemon halves in alongside.',
      'Roast for 35–40 minutes until the skin is deeply golden and the juices run clear. Rest for 5 minutes.',
      'Squeeze the roasted lemon over before serving.',
    ],
  },
  {
    id: 'teriyaki-salmon-bowl',
    name: 'Teriyaki Salmon Bowl',
    emoji: '🍱',
    image: '/recipes/teriyaki-salmon-bowl.jpg',
    tags: ['fish', 'japanese', 'rice', 'healthy'],
    time: '30 min',
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      '2 salmon fillets (skin-on)',
      '300g sushi rice',
      '200g frozen edamame (shelled)',
      '100g wakame seaweed salad',
      '3 tbsp soy sauce',
      '2 tbsp mirin',
      '1 tbsp honey',
      '1 tsp sesame oil',
      '1 garlic clove, grated',
      '1 tsp fresh ginger, grated',
      'Sesame seeds, to finish',
      'Spring onion, sliced, to finish',
    ],
    steps: [
      'Rinse the sushi rice until the water runs clear. Cook according to package instructions, then season lightly with a splash of rice vinegar and a pinch of salt.',
      'Make the teriyaki glaze: combine soy sauce, mirin, honey, garlic, and ginger in a small saucepan over medium heat. Simmer for 3–4 minutes until slightly thickened. Set aside.',
      'Cook the edamame in boiling salted water for 3 minutes, drain, and toss with sesame oil, a splash of soy sauce, and sesame seeds.',
      'Pat the salmon dry. Heat a non-stick pan over high heat with a little oil. Place the salmon skin-side down and press gently. Cook for 4 minutes until the skin is crispy, then flip and cook for 1–2 minutes more. Pour half the glaze over the fillets in the last minute.',
      'Prepare the seaweed salad according to the packet, or simply dress rehydrated wakame with sesame oil, soy sauce, and sesame seeds.',
      'Bowl up: rice first, then salmon, edamame, and seaweed alongside. Drizzle remaining glaze over everything and finish with sesame seeds and spring onion.',
    ],
  },
  {
    id: 'greek-salad',
    name: 'Proper Greek Salad',
    emoji: '🥗',
    tags: ['vegetarian', 'quick', 'light'],
    time: '10 min',
    servings: 2,
    difficulty: 'Easy',
    ingredients: [
      '3 ripe tomatoes, cut into wedges',
      '1 cucumber, roughly chopped',
      '½ red onion, thinly sliced',
      '1 green pepper, sliced',
      '100g Kalamata olives',
      '150g block of feta (not crumbled)',
      '3 tbsp good olive oil',
      '1 tsp dried oregano',
      'Salt and black pepper',
    ],
    steps: [
      'Combine the tomatoes, cucumber, onion, pepper, and olives in a large bowl.',
      'Season with salt and a generous pinch of oregano. Drizzle over the olive oil and toss gently.',
      'Place the block of feta on top — do not mix it in. Finish with more oregano, black pepper, and a drizzle of olive oil.',
      'Serve immediately with crusty bread.',
    ],
  },
]
